---
title: "Rcpp"
author: "David Cooley"
date: "`r Sys.Date()`"
output: 
    html_document:
        toc: true
        toc_float: true
        number_sections: false
        theme: flatly
header-includes: 
    - \usepackage{tikz}
    - \usetikzlibrary{arrows}
vignette: >
  %\VignetteIndexEntry{Rcpp}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}

---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "# ",
  eval = F
)
```

```{r packages, include = TRUE, eval = T}
library(Rcpp)
library(sfheaders)
library(sf)
```



### POINT

```{r, eval = T}

cppFunction(
  includes = '
    #include "sfheaders/sfg/sfg.hpp"
  ',
  code = '
    SEXP a_point( SEXP x ) {
      return sfheaders::sfg::sfg_point( x );
    }
  ',
  depends = "sfheaders"
)

## vector
a_point( c(1,2) )
## single-row matrix
a_point( matrix(c(1,2), ncol = 2) )
## single-row data.frame
a_point( data.frame(x =1, y = 2) )
```


### MULTIPOINT

```{r, eval = T}

cppFunction(
  includes = '
    #include "sfheaders/sfg/sfg.hpp"
  ',
  code = '
    SEXP a_multipoint( SEXP x ) {
      return sfheaders::sfg::sfg_multipoint( x );
    }
  ',
  depends = "sfheaders"
)

x <- 1:2
a_multipoint( x )

x <- matrix(c(1,2,3,4,5,6), ncol = 2)
a_multipoint( x )

x <- data.frame(x = 1:3, y = 4:6)
a_multipoint( x )
```

### LINESTRING

```{r, eval = T}

cppFunction(
  includes = '
    #include "sfheaders/sfg/sfg.hpp"
  ',
  code = '
    SEXP a_linestring( SEXP x ) {
      return sfheaders::sfg::sfg_linestring( x );
    }
  ',
  depends = "sfheaders"
)

x <- 1:2
a_linestring( x )

x <- matrix(c(1,2,3,4,5,6), ncol = 2)
a_linestring( x )

x <- data.frame(x = 1:3, y = 4:6)
a_linestring( x )

x <- data.frame(x = 1:3, y = 4:6, z = 7:9)
a_linestring( x )

```


### MULTILINESTRING


```{r, eval = T}

cppFunction(
  includes = '
    #include "sfheaders/sfg/sfg.hpp"
  ',
  code = '
    SEXP a_multilinestring( SEXP x ) {
      return sfheaders::sfg::sfg_multilinestring( x );
    }
  ',
  depends = "sfheaders"
)

x <- 1:2
a_multilinestring( x )

x <- matrix(c(1,2,3,4,5,6), ncol = 2)
a_multilinestring( x )

x <- data.frame(x = 1:3, y = 4:6)
a_multilinestring( x )

x <- data.frame(x = 1:3, y = 4:6, z = 7:9)
a_multilinestring( x )
```


```{r, eval = T}

cppFunction(
  includes = '
    #include "sfheaders/sfg/sfg.hpp"
  ',
  code = '
    SEXP a_multilinestring( SEXP x, SEXP geometry_cols, SEXP id_col ) {
      return sfheaders::sfg::sfg_multilinestring( x, geometry_cols, id_col );
    }
  ',
  depends = "sfheaders"
)

x <- data.frame(id = c(1,1,2), x = 1:3, y = 4:6, z = 7:9)
a_multilinestring( x, c("x","y"), "id" )

a_multilinestring( x, c("x","y","z"), "id" )

a_multilinestring( x, NULL, "id" )


```

### POLYGON


### MULTIPOLIYGON



#### from C++

There are various overloaded functions for each `sfg`, `sfc` and `sf` types


```{r, eval = F}


cppFunction(
  includes = '
    #include "sfheaders/sfg/sfg.hpp"
  ',
  code = '
    SEXP a_polygon( Rcpp::DataFrame df ) {
      return sfheaders::sfg::sfg_polygon( df );
    }
  ',
  depends = "sfheaders"
)

a_polygon( df )
```

```{r}
cppFunction(
  includes = '
    #include "sfheaders/sfg/sfg.hpp"
  ',
  code = '
    SEXP a_polygon( Rcpp::DataFrame df, Rcpp::StringVector geometry_columns ) {
      return sfheaders::sfg::sfg_polygon( df, geometry_columns );
    }
  ',
  depends = "sfheaders"
)

a_polygon( df, c("x","y") )

a_polygon( df, c("y", "x") )

```

```{r}
cppFunction(
  includes = '
    #include "sfheaders/sfg/sfg.hpp"
  ',
  code = '
    SEXP a_polygon( SEXP x, SEXP geometry_columns ) {
      return sfheaders::sfg::sfg_polygon( x, geometry_columns );
    }
  ',
  depends = "sfheaders"
)

a_polygon( df, c("x","y") )

a_polygon( df, c("y", "x") )

```


```{r}

cppFunction(
  includes = '
    #include "sfheaders/sfg/sfg.hpp"
  ',
  code = '
    SEXP a_polygon( SEXP df, std::string geom_type ) {
      return sfheaders::sfg::to_sfg( df, geom_type );
    }
  ',
  depends = "sfheaders"
)

a_polygon( df, "POLYGON" )

```


### sfc

```{r}
sfc_point( df )

sfc_multipoint( df )

sfc_polygon( df )
```


```{r}

cppFunction(
  includes = '
    #include "sfheaders/sfc/sfc.hpp"
  ',
  code = '
    SEXP a_polygon( SEXP df ) {
      return sfheaders::sfc::sfc_polygon( df );
    }
  ',
  depends = "sfheaders",
  plugins = "cpp11"
)

a_polygon( df )
```

```{r}

cppFunction(
  includes = '
    #include "sfheaders/sfc/sfc.hpp"
  ',
  code = '
    SEXP a_polygon( SEXP df, SEXP geometry_columns ) {
      return sfheaders::sfc::sfc_polygon( df, geometry_columns );
    }
  ',
  depends = "sfheaders",
  plugins = "cpp11"
)

a_polygon( df, c("x","y") )
```


```{r}

df <- data.frame(
  id = c( rep(1, 5), rep(2, 5) )
  , x = 1:10
  , y = 1:10
)

cppFunction(
  includes = '
    #include "sfheaders/sfc/sfc.hpp"
  ',
  code = '
    SEXP a_polygon( SEXP df, SEXP geometry_columns ) {
      return sfheaders::sfc::sfc_polygon( df, geometry_columns );
    }
  ',
  depends = "sfheaders",
  plugins = "cpp11"
)

a_polygon( df, c("x","y") )
```



```{r}

cppFunction(
  includes = '
    #include "sfheaders/sfc/sfc.hpp"
  ',
  code = '
    SEXP a_polygon( SEXP df, SEXP geometry_columns, SEXP polygon_id, SEXP linestring_id ) {
      return sfheaders::sfc::sfc_polygon( df, geometry_columns, polygon_id, linestring_id );
    }
  ',
  depends = "sfheaders",
  plugins = "cpp11"
)

a_polygon( df, c("x","y"), "id", NULL )
```


