# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_calculate_bbox <- function(x) {
    .Call(`_sfheaders_rcpp_calculate_bbox`, x)
}

rcpp_attach_sfc_attributes <- function(sfc, geom_type, bbox, epsg, proj4string, n_empty, precision) {
    invisible(.Call(`_sfheaders_rcpp_attach_sfc_attributes`, sfc, geom_type, bbox, epsg, proj4string, n_empty, precision))
}

rcpp_sfg_dimension <- function(x) {
    .Call(`_sfheaders_rcpp_sfg_dimension`, x)
}

rcpp_get_vec <- function(x, cols) {
    .Call(`_sfheaders_rcpp_get_vec`, x, cols)
}

rcpp_get_mat <- function(x, cols) {
    .Call(`_sfheaders_rcpp_get_mat`, x, cols)
}

rcpp_get_list_mat <- function(x, cols, id) {
    .Call(`_sfheaders_rcpp_get_list_mat`, x, cols, id)
}

rcpp_sfc_point <- function(x, cols) {
    .Call(`_sfheaders_rcpp_sfc_point`, x, cols)
}

rcpp_sfc_multipoint <- function(x, cols, id_col) {
    .Call(`_sfheaders_rcpp_sfc_multipoint`, x, cols, id_col)
}

rcpp_sfc_linestring <- function(x, cols, id_col) {
    .Call(`_sfheaders_rcpp_sfc_linestring`, x, cols, id_col)
}

rcpp_sfc_multilinestring <- function(x, cols, multiline_id, line_id) {
    .Call(`_sfheaders_rcpp_sfc_multilinestring`, x, cols, multiline_id, line_id)
}

rcpp_sfg_point <- function(x, geometry_columns) {
    .Call(`_sfheaders_rcpp_sfg_point`, x, geometry_columns)
}

rcpp_sfg_multipoint <- function(x, geometry_columns) {
    .Call(`_sfheaders_rcpp_sfg_multipoint`, x, geometry_columns)
}

rcpp_sfg_linestring <- function(x, geometry_columns) {
    .Call(`_sfheaders_rcpp_sfg_linestring`, x, geometry_columns)
}

rcpp_sfg_multilinestring <- function(x, geometry_columns, line_id) {
    .Call(`_sfheaders_rcpp_sfg_multilinestring`, x, geometry_columns, line_id)
}

rcpp_sfg_polygon <- function(x, geometry_columns, line_id) {
    .Call(`_sfheaders_rcpp_sfg_polygon`, x, geometry_columns, line_id)
}

rcpp_sfg_multipolygon <- function(x, geometry_columns, polygon_id, line_id) {
    .Call(`_sfheaders_rcpp_sfg_multipolygon`, x, geometry_columns, polygon_id, line_id)
}

rcpp_to_sfg <- function(x, geom_type) {
    .Call(`_sfheaders_rcpp_to_sfg`, x, geom_type)
}

rcpp_other_columns <- function(x, id_cols) {
    .Call(`_sfheaders_rcpp_other_columns`, x, id_cols)
}

rcpp_line_ids <- function(line_ids, unique_ids) {
    .Call(`_sfheaders_rcpp_line_ids`, line_ids, unique_ids)
}

rcpp_subset_dataframe <- function(df, cols, start, end) {
    .Call(`_sfheaders_rcpp_subset_dataframe`, df, cols, start, end)
}

