# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_calculate_bbox <- function(x, geometry_cols) {
    .Call(`_sfheaders_rcpp_calculate_bbox`, x, geometry_cols)
}

rcpp_calculate_z_range <- function(x) {
    .Call(`_sfheaders_rcpp_calculate_z_range`, x)
}

rcpp_calculate_m_range <- function(x, xyzm) {
    .Call(`_sfheaders_rcpp_calculate_m_range`, x, xyzm)
}

rcpp_fill_list <- function(v, line_ids) {
    .Call(`_sfheaders_rcpp_fill_list`, v, line_ids)
}

rcpp_list_sizes <- function(lst) {
    .Call(`_sfheaders_rcpp_list_sizes`, lst)
}

rcpp_list_type <- function(lst) {
    .Call(`_sfheaders_rcpp_list_type`, lst)
}

rcpp_unlist_list <- function(lst) {
    .Call(`_sfheaders_rcpp_unlist_list`, lst)
}

rcpp_sfg_dimension <- function(x, xyzm) {
    .Call(`_sfheaders_rcpp_sfg_dimension`, x, xyzm)
}

rcpp_sfg_to_df <- function(sfg) {
    .Call(`_sfheaders_rcpp_sfg_to_df`, sfg)
}

rcpp_sfc_to_df <- function(sfc) {
    .Call(`_sfheaders_rcpp_sfc_to_df`, sfc)
}

rcpp_sf_to_df <- function(sf, fill = FALSE) {
    .Call(`_sfheaders_rcpp_sf_to_df`, sf, fill)
}

rcpp_sf_to_df_unlist <- function(sf, unlist, fill = FALSE) {
    .Call(`_sfheaders_rcpp_sf_to_df_unlist`, sf, unlist, fill)
}

rcpp_sfc_linestring <- function(x, cols, id_col, xyzm) {
    .Call(`_sfheaders_rcpp_sfc_linestring`, x, cols, id_col, xyzm)
}

rcpp_sfc_multilinestring <- function(x, cols, multiline_id, line_id, xyzm) {
    .Call(`_sfheaders_rcpp_sfc_multilinestring`, x, cols, multiline_id, line_id, xyzm)
}

rcpp_other_columns <- function(x, id_cols, id_col2, id_col3) {
    .Call(`_sfheaders_rcpp_other_columns`, x, id_cols, id_col2, id_col3)
}

rcpp_id_positions <- function(line_ids, unique_ids) {
    .Call(`_sfheaders_rcpp_id_positions`, line_ids, unique_ids)
}

rcpp_subset_dataframe <- function(df, cols, start, end) {
    .Call(`_sfheaders_rcpp_subset_dataframe`, df, cols, start, end)
}

rcpp_concatenate_vectors <- function(vec_1, vec_2) {
    .Call(`_sfheaders_rcpp_concatenate_vectors`, vec_1, vec_2)
}

rcpp_column_positions <- function(m, cols) {
    .Call(`_sfheaders_rcpp_column_positions`, m, cols)
}

rcpp_where_is <- function(to_find, sv) {
    .Call(`_sfheaders_rcpp_where_is`, to_find, sv)
}

rcpp_get_ids <- function(x, id_col) {
    .Call(`_sfheaders_rcpp_get_ids`, x, id_col)
}

