# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test <- function() {
    invisible(.Call(`_sfheaders_test`))
}

rcpp_attach_sfc_attributes <- function(sfc, geom_type, bbox, epsg, proj4string, n_empty, precision) {
    invisible(.Call(`_sfheaders_rcpp_attach_sfc_attributes`, sfc, geom_type, bbox, epsg, proj4string, n_empty, precision))
}

rcpp_to_point <- function(x) {
    .Call(`_sfheaders_rcpp_to_point`, x)
}

rcpp_to_multipoint <- function(x) {
    .Call(`_sfheaders_rcpp_to_multipoint`, x)
}

rcpp_to_multilinestring <- function(df, line_id, geometry_columns) {
    .Call(`_sfheaders_rcpp_to_multilinestring`, df, line_id, geometry_columns)
}

rcpp_to_sfg <- function(x, geom_type) {
    .Call(`_sfheaders_rcpp_to_sfg`, x, geom_type)
}

rcpp_sfg_dimension <- function(x) {
    .Call(`_sfheaders_rcpp_sfg_dimension`, x)
}

rcpp_to_sfc <- function() {
    .Call(`_sfheaders_rcpp_to_sfc`)
}

first_three <- function(x) {
    .Call(`_sfheaders_first_three`, x)
}

rcpp_matrix <- function() {
    .Call(`_sfheaders_rcpp_matrix`)
}

